import os

FUELING_DURATION = 0.5
MAX_DRIVING_PER_DAY = 11
ON_DUTY_WINDOW = 14
MAX_DRIVE_WINDOW = 14
BREAK_AFTER = 8
BREAK_DURATION = 0.5
PICKUP_TIME = 1
DROPOFF_TIME = 1
MAX_CYCLE_HOURS = 70
AVG_SPEED_MPH = 55
MILES_BEFORE_FUEL = 1000
PRE_TRIP_INSPECTION_TIME = 0.5
REST_AFTER_CYCLE = 34
SLEEPER_BREAK_HOURS = 10
START_DUTY_HOUR = 6.5


# OpenRouteService API Key
OPENROUTESERVICE_API_KEY = os.getenv('OPENROUTESERVICE_API_KEY', '')